apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ecr
  namespace: argocd
spec:
  project: aws-ecr
  source:
    repoURL: https://github.com/mandacode-labs/starship-gitops.git
    targetRevision: main
    path: apps/aws-ecr/app
  destination:
    server: https://kubernetes.default.svc
    namespace: ecr-cred
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
