apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-ecr-image-pull-credentials
  namespace: ecr-cred
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical-mandacode-prod
    kind: ClusterSecretStore
  target:
    name: aws-ecr-image-pull-credentials
    creationPolicy: Owner
    template:
      data:
        accessKey: "{{ .access_key }}"
        secretAccessKey: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /aws/ecr/image-pull-credentials/access-key
    - secretKey: secret_key
      remoteRef:
        key: /aws/ecr/image-pull-credentials/secret-key
