apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ecr-credential-sync
  namespace: ecr-cred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-ecr-credential-sync
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-ecr-credential-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-ecr-credential-sync
subjects:
  - kind: ServiceAccount
    name: aws-ecr-credential-sync
    namespace: ecr-cred
