apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openai-api-key
  namespace: traditional-saju
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: openai-api-key
    creationPolicy: Owner
    template:
      data:
        apiKey: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: starship/traditional-saju/openai/apiKey
        property: apiKey
