apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infisical
  sources:
    - repoURL: https://valkey.io/valkey-helm/
      chart: valkey
      targetRevision: "0.9.3"
      helm:
        valueFiles:
          - $values/apps/infisical/valkey/values.yaml

    - repoURL: https://github.com/mandacode-labs/starship-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
