apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: starfrag-starship-gitops-repo
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: starfrag-starship-gitops-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/starfrag-labs/starship-gitops.git
        name: starfrag/starship-gitops
        username: starfrag-labs-argocd
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: github/starfrag-labs/starfrag-labs-argocd
        property: token
