apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  namespace: argocd
spec:
  description: Cert Manager
  destinations:
    - name: in-cluster
      namespace: cert-manager
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/mandacode-labs/starship-gitops.git
    - oci://quay.io/jetstack/charts/cert-manager
