crds:
  enabled: true
  keep: true

replicaCount: 1

podDisruptionBudget:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

startupapicheck:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
