apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-mandacode-prod
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-eso
            namespace: default
            key: clientId
          clientSecret:
            name: infisical-eso
            namespace: default
            key: clientSecret
      hostAPI: https://infisical.console.mandacode.com
      secretsScope:
        projectSlug: mandacode-tcnl
        environmentSlug: prod
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-serengeti-prod
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-eso
            namespace: default
            key: clientId
          clientSecret:
            name: infisical-eso
            namespace: default
            key: clientSecret
      hostAPI: https://infisical.console.mandacode.com
      secretsScope:
        projectSlug: serengeti-0c0-a
        environmentSlug: prod
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-starfrag-prod
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-eso
            namespace: default
            key: clientId
          clientSecret:
            name: infisical-eso
            namespace: default
            key: clientSecret
      hostAPI: https://infisical.console.mandacode.com
      secretsScope:
        projectSlug: starfrag-o-ft2
        environmentSlug: prod
