apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-serengeti-prod
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-eso
            key: clientId
          clientSecret:
            name: infisical-eso
            key: clientSecret
      hostAPI: https://infisical.console.mandacode.com
      secretsScope:
        projectSlug: serengeti
        environmentSlug: prod
