apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-secrets
  namespace: infisical
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: infisical-secrets
    creationPolicy: Owner
    template:
      data:
        AUTH_SECRET: "{{ .auth_secret }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        SITE_URL: "https://infisical.console.mandacode.com"
        DB_CONNECTION_URI: "postgresql://app:{{ .db_password }}@infisical-cnpg-cluster-rw.infisical.svc.cluster.local:5432/infisical"
        REDIS_URL: "redis://:{{ .redis_password }}@infisical-valkey.infisical.svc.cluster.local:6379"
  data:
    - secretKey: auth_secret
      remoteRef:
        key: starship/infisical/secrets
        property: auth_secret
    - secretKey: encryption_key
      remoteRef:
        key: starship/infisical/secrets
        property: encryption_key
    - secretKey: db_password
      remoteRef:
        key: starship/infisical/cnpg/user/app
        property: password
    - secretKey: redis_password
      remoteRef:
        key: starship/infisical/valkey/auth
        property: password
