apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-user-gitea
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical-mandacode-prod
    kind: ClusterSecretStore
  target:
    name: db-user-gitea
    creationPolicy: Owner
    template:
      data:
        username: gitea
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /gitea/cnpg/users/gitea/password
