apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: harbor
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.18.2"
      helm:
        valueFiles:
          - $values/apps/harbor/app/values.yaml

    - repoURL: https://github.com/mandacode-labs/starship-gitops.git
      targetRevision: main
      ref: values

    # Kustomization
    - repoURL: https://github.com/mandacode-labs/starship-gitops.git
      targetRevision: main
      path: apps/harbor/app

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
