apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-user-starship-harbor
  namespace: harbor
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical-mandacode-prod
    kind: ClusterSecretStore
  target:
    name: aws-user-starship-harbor
    creationPolicy: Owner
    template:
      data:
        REGISTRY_STORAGE_S3_ACCESSKEY: "{{ .access_key }}"
        REGISTRY_STORAGE_S3_SECRETKEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: /harbor/registry/s3/access-key
    - secretKey: secret_key
      remoteRef:
        key: /harbor/registry/s3/secret-key
