apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  commonName: harbor.harbor.svc.cluster.local
  dnsNames:
    - harbor.harbor.svc.cluster.local
    - harbor.harbor.svc
    - harbor
  secretName: harbor-tls
  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: starship-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
