apiVersion: "gateway.networking.k8s.io/v1"
kind: HTTPRoute
metadata:
  name: harbor-route
  namespace: harbor
spec:
  hostnames:
    - "registry.mandacode.com"
  parentRefs:
    - name: eg
      namespace: default
      sectionName: "https-registry"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: harbor
          namespace: harbor
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: harbor-backend-tls
  namespace: harbor
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: harbor
      sectionName: https
  validation:
    caCertificateRefs:
      - name: starship-root-ca
        group: ""
        kind: Secret
    hostname: harbor.harbor.svc.cluster.local
