apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-app
  namespace: harbor
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::273216125096:role/StarshipHarborAppDataAccess
automountServiceAccountToken: true
