apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metrics-server
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Metrics Server project
  destinations:
    - name: in-cluster
      namespace: metrics-server
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://kubernetes-sigs.github.io/metrics-server
    - https://github.com/mandacode-lab/starship-gitops.git
