apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: global-cnpg
  namespace: argocd
spec:
  description: Global CloudNativePG Cluster Project
  destinations:
    - name: in-cluster
      namespace: global-database
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://cloudnative-pg.github.io/charts
    - https://github.com/mandacode-labs/starship-gitops.git
