apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-mandacode-tls
  namespace: default
spec:
  secretName: registry-mandacode-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - registry.mandacode.com
