apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-user-starfrag-tarot
  namespace: global-database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical-mandacode-prod
    kind: ClusterSecretStore
  target:
    name: cnpg-user-starfrag-tarot
    creationPolicy: Owner
    template:
      data:
        username: starfrag-tarot
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: /global-database/users/admin/password
