apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner-token
  namespace: gitea-actions
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical-mandacode-prod
    kind: ClusterSecretStore
  target:
    name: gitea-runner-token
    creationPolicy: Owner
    template:
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: /gitea/token/runner/act-runner
