apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metrics-server
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Metrics Server
  destinations:
    - name: in-cluster
      namespace: kube-system
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://kubernetes-sigs.github.io/metrics-server
    - https://github.com/mandacode-labs/starship-gitops.git
