apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: "cnpg-cluster-keycloak-rw.keycloak.svc.cluster.local"
    usernameSecret:
      name: db-user-app
      key: username
    passwordSecret:
      name: db-user-app
      key: password
  ingress:
    enabled: false
  http:
    httpEnabled: true
  hostname:
    hostname: idp.mandacode.com
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
