apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: keycloak
  namespace: argocd
spec:
  description: Keycloak Project
  destinations:
    - name: in-cluster
      namespace: keycloak
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/mandacode-lab/starship-gitops.git
    - https://cloudnative-pg.github.io/charts
