apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: external-secrets
  sources:
    # Helm chart for External Secrets Operator
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.0.0
      helm:
        valueFiles:
          - $values/infra/external-secrets/values.yaml
    # Reference for values file
    - repoURL: https://github.com/mandacode-labs/starship-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
