apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-secrets
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: External Secrets Project
  destinations:
    - name: in-cluster
      namespace: external-secrets
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://charts.external-secrets.io
    - https://github.com/mandacode-labs/starship-gitops.git
