apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-sync
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mandacode-labs/starship-gitops.git
        revision: main
        directories:
          - path: apps/*

  template:
    metadata:
      name: '{{path.basename}}-sync'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: https://github.com/mandacode-labs/starship-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
