apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serengeti
  namespace: argocd
spec:
  project: serengeti
  sources:
    # Kustomization for serengeti
    - repoURL: https://github.com/serengeti-sh/starship-gitops.git
      targetRevision: main
      path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: serengeti
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
