apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: serengeti
  namespace: argocd
spec:
  description: Serengeti GitOps
  destinations:
    - name: in-cluster
      namespace: serengeti
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/serengeti-sh/starship-gitops.git
