apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: serengeti-starship-gitops-repo
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: serengeti-starship-gitops-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://git.mandacode.com/serengeti/starship-gitops.git
        name: serengeti/starship-gitops
        username: argocd-gitops
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: starship/gitea/user/sauce/token/argocd-gitops
        property: token
