apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-backup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: gitea
  source:
    repoURL: https://github.com/mandacode-labs/starship-gitops.git
    targetRevision: main
    path: apps/gitea/backup

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
