apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-backup
  namespace: gitea
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::273216125096:role/StarshipGiteaBackup
automountServiceAccountToken: true
