apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infisical
  namespace: argocd
spec:
  description: Infisical Secrets Management
  destinations:
    - name: in-cluster
      namespace: infisical
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/mandacode-labs/starship-gitops.git
    - https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    - https://cloudnative-pg.github.io/charts
    - https://valkey.io/valkey-helm/
