apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: gitea
  sources:
    - repoURL: https://dl.gitea.com/charts/
      chart: gitea
      targetRevision: "12.5.0"
      helm:
        valueFiles:
          - $values/apps/serengeti-gitea/values.yaml

    - repoURL: https://github.com/mandacode-labs/starship-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: serengeti-gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
