apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitea
  namespace: argocd
spec:
  description: Gitea Git Service
  destinations:
    - name: in-cluster
      namespace: serengeti-gitea
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/mandacode-labs/starship-gitops.git
    - https://cloudnative-pg.github.io/charts
    - https://dl.gitea.com/charts/
