apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-renovate
  namespace: argocd
spec:
  project: gitea
  source:
    repoURL: https://github.com/mandacode-labs/starship-gitops.git
    targetRevision: main
    path: apps/gitea/renovate
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
