apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-credentials
  namespace: gitea
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: renovate-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: starship/gitea/user/renovate-bot
        property: token
