apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-user-admin
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: gitea-user-admin
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: starship/gitea/user/admin
        property: username
    - secretKey: password
      remoteRef:
        key: starship/gitea/user/admin
        property: password
