apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-cnpg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: gitea
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: 0.5.0
      helm:
        valueFiles:
          - $values/apps/gitea/cnpg-values.yaml

    - repoURL: https://github.com/mandacode-labs/starship-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
